### ISSUE TITLE
unable to upload .tsp data format and to get total tour length

### ISSUE THREAD

**Issue by ayockishaya** [MichelDeudon/encode-attend-navigate#1]
Please i need an urgent assistance on the following point.
1. How do i read TSP data format( belin53.tsp) to use for training and prediction.
2. How do i get the total tour length( belin53.tsp) for each of the tsp dataset

Thanks

**Comment by MichelDeudon** [comment]
Hi ayockishaya,
You need to convert your data set 2D eucliedean TSP, meaning converting your cities to coordinates (x,y) in euclidean space. From that things should run smoothly.

Best,
MD
