### ISSUE TITLE
Dropout unused

### ISSUE THREAD

**Issue by astariul** [MichelDeudon/encode-attend-navigate#2]
Why dropout is not used ? 

(Default value is 0) : https://github.com/MichelDeudon/encode-attend-navigate/blob/9339a22788acefb1141c615ec9b6fc01eacb47f2/code/utils.py#L68

---

Is it due to empirical results being better without dropout ? **Did you try other dropout rates ?**

**Comment by MichelDeudon** [comment]
Didn't observe significant improvements with dropout.
