### ISSUE TITLE
 ❓ Separate encoder for actor and critic

### ISSUE THREAD

**Issue by cola-nicolas** [MichelDeudon/encode-attend-navigate#3]
As far as I understand the code, it seems `actor` and `critic` use 2 distinct encoders.

What's the reason behind this choice ? Wouldn't it be better to have a shared encoder ?

@MichelDeudon

**Comment by MichelDeudon** [comment]
No particular choice, if not to keep things separate. An alternative to using a neural network (with or without shared encoder), would be using a simple moving average or another heuristic as proposed by @WooterKool in the paper below. I think this would reduce the variance of the gradients and improve performance. Please feel free to compare these different methods and open a pull request. Thank you.

https://arxiv.org/abs/1803.08475
